linters:
  enable-all: true
  disable:
    - gofmt

linters-settings:
  gocritic:
    enabled-tags: ["diagnostic", "experimental", "opinionated"]

  gofumpt:
    mode: "fix"

run:
  deadline: "10m"
  tests: true
  skip-dirs-use-default: true

output:
  format: colored-line-number

linters-exhaustive-list: true
